### ISSUE TITLE
Issues on OSX

### ISSUE THREAD

**Issue by podarok** [robinhad/ukrainian-ai#1]
Hi

Trying to run 

```sh
git clone https://github.com/robinhad/ukrainian-ai.git
cd ukrainian-ai/
python3.9 -m pip install --user -r requirements.txt
python3.9 app.py
```

Result

```
MacBook-Pro-Andrii:ukrainian-ai podarok$ python3.9 app.py
Traceback (most recent call last):
  File "/private/var/ai/ukrainian-ai/app.py", line 5, in <module>
    from ukrainian_tts.tts import TTS, Voices, Stress
  File "/Users/podarok/Library/Python/3.9/lib/python/site-packages/ukrainian_tts/tts.py", line 4, in <module>
    from espnet2.bin.tts_inference import Text2Speech
  File "/Users/podarok/Library/Python/3.9/lib/python/site-packages/espnet2/bin/tts_inference.py", line 17, in <module>
    from typeguard import check_argument_types
ImportError: cannot import name 'check_argument_types' from 'typeguard' (/Users/podarok/Library/Python/3.9/lib/python/site-packages/typeguard/__init__.py)
```

**Comment by robinhad** [comment]
Fixed by upgrading TTS package that caused a problem
