### ISSUE TITLE
_pickle.UnpicklingError: could not find MARK - after #1 fixed

### ISSUE THREAD

**Issue by podarok** [robinhad/ukrainian-ai#3]
Torch 1.13.1

```sh
MacBook-Pro-Andrii:ukrainian-ai podarok$ accelerate launch  app.py
[11:08:12] WARNING  The following values were not passed to `accelerate launch` and had defaults used instead:       launch.py:890
                            `--num_cpu_threads_per_process` was set to `4` to improve out-of-box performance when                 
                    training on CPUs                                                                                              
                    To avoid this warning pass in values for each of the problematic parameters or run `accelerate                
                    config`.                                                                                                      
downloading uk/mykyta/vits-tts
Found ./model.pth. Skipping download...
Found ./config.yaml. Skipping download...
/Users/podarok/Library/Python/3.9/lib/python/site-packages/espnet2/gan_tts/vits/monotonic_align/__init__.py:19: UserWarning: Cython version is not available. Fallback to 'EXPERIMETAL' numba version. If you want to use the cython version, please build it as follows: `cd espnet2/gan_tts/vits/monotonic_align; python setup.py build_ext --inplace`
  warnings.warn(
Traceback (most recent call last):
  File "/private/var/ai/ukrainian-ai/app.py", line 9, in <module>
    tts = TTS(device="cpu") # can try gpu, mps
  File "/Users/podarok/Library/Python/3.9/lib/python/site-packages/ukrainian_tts/tts.py", line 42, in __init__
    self.__setup_cache(cache_folder)
  File "/Users/podarok/Library/Python/3.9/lib/python/site-packages/ukrainian_tts/tts.py", line 108, in __setup_cache
    self.synthesizer = Text2Speech(
  File "/Users/podarok/Library/Python/3.9/lib/python/site-packages/espnet2/bin/tts_inference.py", line 92, in __init__
    model, train_args = TTSTask.build_model_from_file(
  File "/Users/podarok/Library/Python/3.9/lib/python/site-packages/espnet2/tasks/abs_task.py", line 1833, in build_model_from_file
    model.load_state_dict(torch.load(model_file, map_location=device))
  File "/usr/local/lib/python3.9/site-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.9/site-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: could not find MARK
```

Same with torch 2.0.0

```sh
MacBook-Pro-Andrii:ukrainian-ai podarok$ accelerate launch  app.py
[11:04:28] WARNING  The following values were not passed to `accelerate launch` and had defaults used instead:       launch.py:890
                            `--num_cpu_threads_per_process` was set to `4` to improve out-of-box performance when                 
                    training on CPUs                                                                                              
                    To avoid this warning pass in values for each of the problematic parameters or run `accelerate                
                    config`.                                                                                                      
/Users/podarok/Library/Python/3.9/lib/python/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
downloading uk/mykyta/vits-tts
Found ./model.pth. Skipping download...
Found ./config.yaml. Skipping download...
/Users/podarok/Library/Python/3.9/lib/python/site-packages/espnet2/gan_tts/vits/monotonic_align/__init__.py:19: UserWarning: Cython version is not available. Fallback to 'EXPERIMETAL' numba version. If you want to use the cython version, please build it as follows: `cd espnet2/gan_tts/vits/monotonic_align; python setup.py build_ext --inplace`
  warnings.warn(
Traceback (most recent call last):
  File "/private/var/ai/ukrainian-ai/app.py", line 9, in <module>
    tts = TTS(device="cpu") # can try gpu, mps
  File "/Users/podarok/Library/Python/3.9/lib/python/site-packages/ukrainian_tts/tts.py", line 42, in __init__
    self.__setup_cache(cache_folder)
  File "/Users/podarok/Library/Python/3.9/lib/python/site-packages/ukrainian_tts/tts.py", line 108, in __setup_cache
    self.synthesizer = Text2Speech(
  File "/Users/podarok/Library/Python/3.9/lib/python/site-packages/espnet2/bin/tts_inference.py", line 92, in __init__
    model, train_args = TTSTask.build_model_from_file(
  File "/Users/podarok/Library/Python/3.9/lib/python/site-packages/espnet2/tasks/abs_task.py", line 1833, in build_model_from_file
    model.load_state_dict(torch.load(model_file, map_location=device))
  File "/Users/podarok/Library/Python/3.9/lib/python/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/Users/podarok/Library/Python/3.9/lib/python/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: could not find MARK
```

Seems like some other dependencies also should be used older.

**Comment by podarok** [comment]
same with latest code
